config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/events/:id/invite', to: 'events#invite', as: 'invite_event'
  get '/events/:id/attend', to: 'events#attend', as: 'attend_event'
  get '/users/invitations', to: 'users#invited_events', as: 'invited_events'

  resources :users, only: %i[create show]
  resources :events, only: %i[index new create show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitations, foreign_key: :event_id, dependent: :destroy
  has_many :attendees, through: :invitations, source: :attendee
  has_one_attached :image

  validates :date, presence: true
  validates :location, presence: true
  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 340 }

  scope :upcoming, -> { where('date >= ?', DateTime.now) }
  scope :past, -> { where('date < ?', DateTime.now) }
end

app/models/invitation.rb
# frozen_string_literal: true

class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id, dependent: :destroy
  has_many :invitations, foreign_key: :attendee_id, dependent: :destroy
  has_many :invited_events, through: :invitations, source: :event
  has_many :attended_events, through: :invitations, source: :event

  before_save :downcase_email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  # Converts email to all lower-case.
  def downcase_email
    email.downcase!
  end

  def upcoming_events
    attended_events.where('date >= ? AND accepted = ?', DateTime.now, true)
  end

  def previous_events
    attended_events.where('date < ? AND accepted = ?', DateTime.now, true)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionHelper
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  include EventsHelper
  before_action :find_event, only: %i[show]
  before_action :load_current_user, only: %i[index]

  def index
    @passed_events = Event.past.paginate(page: params[:passed_page], per_page: 10).order('date DESC')
    @coming_events = Event.upcoming.paginate(page: params[:upcoming_page], per_page: 10).order('date ASC')
    @from_events_controller = true
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    event_days_to_start @event
    if @event.save
      flash[:success] = "Congrats!! #{current_user.name}, your event will start in #{@days} days!!!.."
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def invite
    @event = Event.find_by(id: params[:id])
    @invitation = Invitation.new(attendee_id: params[:user_id], event_id: params[:id])
    attendee = User.find_by(id: params[:user_id])

    if @invitation.save
      flash[:success] = "Great!! #{attendee.name} has recieved your invitation to this event."
    else
      flash[:danger] = 'There was an error trying to add a new guest to your event!!!'
    end

    redirect_to event_path(@event)
  end

  def attend
    @invitation = Invitation.find_by(attendee_id: current_user.id, event_id: params[:id])

    if @invitation.update(accepted: true)
      flash[:success] = "Congrats #{current_user.name}, you are attending to this event!!.. #{@invitation.event.name} hosted by #{@invitation.event.creator.name}"
      redirect_to invited_events_path
    else
      render event_path(@event)
    end
  end

  def show; end

  private

  def event_params
    params.require(:event).permit(:location, :date, :description, :name, :image)
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def load_current_user
    User.includes(:attended_events, :invitations, :events) if logged_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  # include SessionHelper

  def new
    redirect_to current_user if logged_in?
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user
      log_in @user
      flash[:success] = 'Welcome back to your Private Events!!!'
      redirect_to @user
    else
      flash.now[:danger] = 'Check your email!'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:info] = 'Log in to create new events!!'
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  # respond_to :html, :json
  # respond_to :html, :xml, :json
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'You have created an account!'
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @my_events = @user.events.paginate(page: params[:page], per_page: 4).order('date DESC')
    @events = []
    @events = User.find(params[:id]).previous_events if params[:passed].present?
    @events = User.find(params[:id]).upcoming_events if params[:coming].present?
    respond_to do |format|
      format.json do
        if request.xhr?
          render :json => {:success => true, :html => (render_to_string("_events", :formats => [:html], :layout => false, :locals => {:events => @events})), data: @events}
        end
      end
 
      format.html {   }
    end
  end

  def invited_events
    @invited_events = Event.where(id: Invitation.all.where(attendee_id: current_user.id,
                                                           accepted: false).pluck(:event_id))
    @accepted_button = true
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def event_days_to_start event
    @days = (TimeDifference.between(event.date, DateTime.now).in_days).round()
  end
end

app/helpers/session_helper.rb
# frozen_string_literal: true

module SessionHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
    @current_user
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/events/_event.html.erb
<div class="events">
  <div class="date-host">
    <strong><%= event.date.strftime('%Y %b %d %I:%M%p') %></strong>
    <% if @from_events_controller %>
      <small><%= event.creator.name %></small>
    <% end %>
    <div class="date-start">
      <% if event.date > DateTime.now %>
      <small>
        This event will start in:
      </small>
      <small>
        <span class="label label-info"> <%= TimeDifference.between(event.date, DateTime.now).humanize %></span>
      </small>
      <% else %>
        <small>
          <span class="label label-danger">Passed Event!</span>
        </small>
      <% end %>
    </div>
  </div>
  <%= image_tag event.image if event.image.present? %>

  <div class="details-event">
    <div class="title">
      <p><%= event.name %></p>
    </div>
    <div class="details">
      <div class="event-details">
        <p>
          <%= fa_icon "map-marker" %>
          <%= event.location %>
        </p>
        <p class="description"><%= event.description %></p>
        <span class="label label-danger"><%= pluralize(event.invitations.where(accepted: true).count, "person") %> are attending to this event!</span>
        <% if logged_in? && current_user.id != event.creator_id %>
          <% if current_user.attended_events.any?%>
            <% if current_user.attended_events.ids.include? event.id && !@accepted_button%>
              <span class="label label-success">Attending</span>
            <% end %>
          <% end %>
        <% end %>
        <% if logged_in? && current_user.id == event.creator_id %>
        <span class="label label-success"><%= event.creator.name %>, you are hosting this event!!</span>
        <% else %>
          <span class="label label-primary"><%= event.creator.name %> is the host</span>
        <% end %>
      </div>
      <div class="button-details">
        <% unless @accepted_button %>
          <%= link_to "See Details", event_path(event) %>
        <% end %>
        <% if @accepted_button %>
          <%= link_to "Accept event invitation", attend_event_path(event), class: 'event_button', method: :get %>
        <% end%>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<%= javascript_pack_tag 'script' %>

<div class="container">
  <div class="event_header">
    <h3>Check out the most popular events!!!</h3>
  </div>
  
  <div class="stiky-navigation">
    <%= link_to "Passed Events", "#", id: "passed"%>
    <%= link_to "Upcoming Events", "#", id: "up_coming"%>
  </div>
  
  <div class="main_event">
    <div id="upcomingEvents">
      <h2>Upcoming Events</h2>
      <div class="divider"></div>
      <div class="pagination-events">
        <%= will_paginate @coming_events, :param_name => 'upcoming_page' %>
      </div>
      <%= render @coming_events.includes(:creator, :attendees, :invitations) %>
    </div>
    
    <div id="passedEvents">
      <h2>Passed Events</h2>
      <div class="divider"></div>
      <div class="pagination-events">
        <%= will_paginate @passed_events, :param_name => 'passed_page' %>
      </div>
      <%= render @passed_events.includes(:creator, :attendees, :invitations) %>
    </div>
    
  </div>
</div>  

app/views/events/new.html.erb
<%= provide(:title, "New Event") %>

<div class="new-event-container">
  <h1>Create your new event!!!!</h1>
  <%= form_for(@event, local: true, multipart: true) do |f| %>
    <%= render 'shared/errors', obj: @event %>
    <div class="form-group" >
      <%= f.label :name, "Event Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  
    <div class="form-group" >
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
    </div>
  
    <div class="form-group" >
      <%= f.label :date %>
      <%= f.datetime_field :date, class: "form-control" %>
    </div>
  
    <div class="form-group" >
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group" >
      <%= f.label :image %>
      <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-max-file-size="2" data-dropzone-max-files="1">
        <%= f.file_field :image, class: "form-control", direct_upload: true, data: { target: "dropzone.input" } %>
        <div class="dropzone-msg dz-message meedsclick text-gray-600">
          <h3 class="dropzone-msg-title">Drag here the picture of your new event!!!</h3>
          <span class="dropzone-msg-desc text-sm">2 MB file size maximum. Allowed files types jpg and png..</span>
        </div>
      </div>
    </div>
  
    <div class="form-group" >
      <%= f.submit "Create", class: "btn btn-success" %>
    </div>
  <% end %>

</div>

app/views/events/show.html.erb
<div class="container">
  <div class="show_event">
    <div class="header">
      <h2>
        <%= @event.creator.name %>'s event.
      </h2>
    </div>
    <div class="body">
      <p>
        <%= fa_icon "map-marker" %>
        <%= @event.location %>
      </p>
      <p class="description"><%= @event.description %></small></p>
    </div>
    <div class="footer">
      <span class="label label-success"><%= @event.date.strftime('%Y %B %d %I:%M%p') %></span>
    </div>
  </div>

  <% if logged_in? && current_user.id == @event.creator_id %>
    <span class="label label-success">You have <%= @event.invitations.where(accepted: false).count %> invitations pending... </span>
  <% end %>
  <br>
  <br>
  <% if logged_in? && current_user.id == @event.creator_id %>
    <div class="dropdown" style="display:inline-block;">
      <% if User.where.not(id: [current_user.id] + Invitation.all.where(event_id: @event.id).pluck(:attendee_id)).count != 0%>
        <button id="country-select-btn" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Invite people to your event
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <% User.where.not(id: [current_user.id] + Invitation.all.where(event_id: @event.id).pluck(:attendee_id)).each do |user| %>
              <%= content_tag(:li, link_to(user.name, invite_event_path(id: @event.id, params: { user_id: user.id }), method: :get)) %>
            <% end %>
          </ul>
      <% end %>
    </div>
  <% end %>
  <% if @event.invitations.where(accepted: true).any? %>
  <div class="people-attending-container">
      <h2>People attending to this event:</h2>
      <% @event.invitations.where(accepted: true).each do |attendee| %>
        <span class="label label-primary"><%= attendee.attendee.name %> </span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="header-container">
  <nav>
    <div class="nav-title">
      <p>Private Events</p>
    </div>
    <div class="separator"></div>
    <ul>
      <%= link_to "Events" , events_path %>

      <% if logged_in? %>
        <%= link_to "My events" , current_user, params: { coming: 'true' }, class: "comming_request"%>
        <%= link_to invited_events_path, class: "invites-event" do %>
          <span class="fa-stack">
            <i class="fa fa-square-o fa-stack-2x"></i>
            <i class="fa fa-dallar fa-stack-1x"><%= current_user.invitations.where(accepted: false).count %></i>
          </span>Invites
        <% end %>
        <%= link_to "Logout" , logout_path %>
      <% else %>
        <%= link_to "Login" , login_path %>
        <%= link_to "SignUp" , signup_path %>
      <% end %>
    </ul>
    <p class="user-name">
      <% if current_user %>
        <%= current_user.name %>
      <% end %>
    </p>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<%= javascript_pack_tag 'messages' %>
<div class="messages-container">
  <% if flash.any? %>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%="#{name}"%> alert-dismissible show' role="alert">
        <%= msg %>
        <button type="button" id="close" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible show" role="alert">
      <button type="button" id="close" class="close" data-dismiss="alert" arai-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h5><%= pluralize(obj.errors.count, "error") %>.</h5>
        <ul>
          <strong>Errors!</strong>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
<% end %>

app/views/users/_events.html.erb
<% @events.each do |e| %>
  <div class="coming_and_passed_events">
    <div class="header">
      <h2>
        <%= e.name %>
      </h2>
    </div>
    <div class="body">
      <p>
        <%= fa_icon "map-marker" %>
        <%= e.location %>
      </p>
      <span class="label label-success"><%= e.creator.name %> is hosting this event!!</span>
      <p class="description"><%= e.description %></p>
    </div>
    <div class="footer">
      <span class="label label-info"><%= e.date.strftime('%Y %B %d %I:%M%p') %></span>
      <span class="label label-primary"><%= link_to 'Details', event_path(e) %></span>
    </div>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/invited_events.html.erb
<div class="container">
  <br/>
  <% if @invited_events.any? %>
    <%= render @invited_events %>
  <% else %>
    <div class="alert alert-info alert-dismissible show" role="alert">
      <button type="button" id="close" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <p>You don't have invitations!!</p>
    </div>
    <div class="start-event-container">
      <h2>Start new Events and invite your friends!!</h2>
      <%= link_to 'Create a New Event', new_event_path, class: "create-event" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide(:button_text, 'Sign up') %>

<div class="form-signup-container">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/errors', obj: @user %>
    <h2>Sign In to Private Events</h2>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  
    <%= f.submit yield(:button_text) %>
  <% end %>

</div>

app/views/users/show.html.erb
<%= javascript_pack_tag 'eventsasync' %>
<%= javascript_pack_tag 'counter_events' %>
<% provide(:title, @user.name) %>

<div class="main_events">
  <div class="row">
    <div class="col-md-7 events-container">
      <% if logged_in? && @user.id == current_user.id %>
        <%= link_to "Create a new event", new_event_path, class: "create-event" %>
      <% end %>
      <% if @user.events.any? %>
        <br>
        <div class="user-event-details">
          <span class="label label-success"><span class="events_counter"><%= @user.events.count%></span> EVENTS IN YOUR DASHBOARD!!</span>
        </div>
        <div class="user_events_pagination">
          <%= will_paginate @my_events %>
        </div>
        <%= render @my_events %>
      <% else %>
        <div class="create-event-container">
          <strong>You have no events!!!</strong>
        </div>
      <% end %>
    </div>
    <aside class="col-md-5">
      <section class="user_info">
        <h1>
          <%= @user.name %>
        </h1>
        <div>
          <h5>You have these events in your schedule!!</h5>
          <div class="event-buttons" id='<% @user.id %>'>
            <%= link_to 'Upcoming events', user_path(@user, params: { coming: 'true' }), class: "comming_request", :remote => true %>
            <%= link_to 'Passed events', user_path(@user, params: { passed: 'true' }), class: "passed_request", :remote => true %>
          </div>
          <div class="content_custom_event">
        
          </div>
        </div>
      </section>
    </aside>
  </div>

</div>